// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Context;

#nullable disable

namespace QuizApp.Migrations;

[DbContext(typeof(QuizAppDbContext))]
partial class QuizAppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("QuizApp.Models.Answer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AnswerText")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsCorrect")
                    .HasColumnType("bit");

                b.Property<int>("QuestionId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("QuestionId");

                b.ToTable("Answers");
            });

        modelBuilder.Entity("QuizApp.Models.Question", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("QuestionText")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Questions");
            });

        modelBuilder.Entity("QuizApp.Models.Answer", b =>
            {
                b.HasOne("QuizApp.Models.Question", null)
                    .WithMany("Answers")
                    .HasForeignKey("QuestionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("QuizApp.Models.Question", b =>
            {
                b.Navigation("Answers");
            });
#pragma warning restore 612, 618
    }
}